export const columns = [
    {
        field: "created_at",
        header: "Fecha Entrada",
        filter: true,
        sortable: true,
        type: "date",
    },
    {
        field: "cliente_name",
        header: "Nombre del pasajero",
        filter: true,
        sortable: true,
    },
    {
        field: "adults",
        header: "Pasajeros",
        filter: true,
        sortable: true,
    },
    {
        field: "cliente_building",
        header: "Edificio u Hotel",
        filter: true,
        sortable: true,
    },
    {
        field: "service",
        header: "Actividad",
        filter: true,
        sortable: true,
    },
    {
        field: "date",
        header: "Fecha de la Actividad",
        filter: false,
        type: "date",
        sortable: true,
    },
    {
        field: "channel.name",
        header: "Canal de venta",
        filter: true,
        sortable: true,
    },
    {
        field: "proveedors_names",
        header: "proveedores",
        class: "text-center font-semibold text-sm",
        filter: true,
    },
    {
        field: "status",
        header: "Estado",
        filter: true,
        sortable: true,
        type: "tag",
        filtertype: "EQUALS",
        class: "text-center uppercase",
        severitys: [
            { text: "RESERVADO", severity: "info", class: "" },
            { text: "CAMBIO DE FECHA", class: "bg-gray-200 font-bold" },
            { text: "COMPLETADA", severity: "success", class: "" },
            { text: "NO SHOW", severity: "warn", class: "" },
            { text: "REUBICADO", severity: "warn", class: "" },
            { text: "CANCELADA", severity: "danger", class: "animate-pulse" },
            { text: "PROBLEMATICA", severity: "danger", class: "animate-pulse" },
            { text: "SIN CONFIRMAR", severity: "danger" },
        ],
    },
];
